on:
  push:
    branches:
      - master

# TODO: setup a job that does the preamble stuff or something
jobs:
  run_ubuntu_tests:
    runs-on: ubuntu-latest
    env:
      VARIABLE_ONE: hello
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Run Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :cleanNativeTest :nativeTest --tests "net.ormr.envvar.TestThing"